name: Build & Deploy to Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy_fargate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_FARGATE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and Push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest

      - name: Deploy Fargate Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: fargate-task-def.json
          service: ${{ secrets.AWS_FARGATE_SERVICE }}
          cluster: ${{ secrets.AWS_FARGATE_CLUSTER }}
