name: Build & Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_LAMBDA }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Lambda Function
        run: |
          zip -r lambda.zip .

      - name: Deploy to Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          zip-file: lambda.zip
