name: Update Go Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set repository name as module name
        run: |
          NEW_MODULE_NAME="${{ github.repository }}"
          go mod edit -module $NEW_MODULE_NAME
          go mod tidy

      - name: Update import paths in the source code
        run: |
          OLD_PACKAGE_NAME="urbanmedia/go-cli-boilerplate"
          NEW_PACKAGE_NAME="${{ github.repository }}"
          # Find and replace the old package name with the new one in the Go files
          find . -type f -name '*.go' -exec sed -i "s|$OLD_PACKAGE_NAME|$NEW_PACKAGE_NAME|g" {} +

      - name: Commit and push updated go.mod
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Go module name"
          git push

      - name: Delete the GitHub Actions workflow file
        run: |
          git rm .github/workflows/update-go-module.yaml
          git commit -m "Remove workflow after execution"
          git push
